[project]
name = "cloudai"
version = "0.6"

[tool.ruff]
target-version = "py39"
line-length = 120

[tool.ruff.lint]
select = ["I", "B", "E", "F", "SIM", "W", "C90", "EXE"]

[tool.ruff.format]
indent-style = "space"
