# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name = "sleep-scenario"

pre_test = "healthy-nodes"

# [[Tests]]
# id = "node-health-test"
# time_limit = "00:01:00"
# test_name = "sleep_10"
# num_nodes = 40
# nodes = [] # 39, iter 1
# nodes = [] # 38, iter 2
# nodes = [] # 37, iter 3

# nccl-sanity generate nodes-list.txt with good nodes. min_nodes definition here???

[[Tests]]
id = "main-test"
time_limit = "00:01:00"
test_name = "sleep_20"
num_nodes = 40          # <-- serves as min_nodes, max_nodes will be taken from node-health-test.num_nodes
  # [[Tests.dependencies]]
  # type = "faulty-nodes-less"
  # id = "node-health-test"

# THE FLOW
# When "node-health-test" is done, we take "main-test":
# 1. Check, if "node-health-test" is successful, if so — simply run "main-test"
# 2. If "node-health-test" is failed, we extract the nodes that a faulty and calculate number of "good" nodes
# in-a-loop:
# 11. exclude one faulty node from the "node-health-test" job
# 12. get the list of "good" nodes
# 13. If the number of "good" nodes is < "main-test.num_nodes", job fails
# 14. If the number of "good" nodes is >= "main-test.num_nodes", re-run "node-health-test" on smaller number of nodes
# 3. we run "main-test" on the "good" nodes using "main-test.nodes" field

# ???
# 1. What if "good" nodes are allocated between our runs?
# 2. This introduces an expectation on "node-health-test" job type, should be NCCL only
